ARG version
FROM almalinux:${version:-10}
ARG sudheer="lazyboy"
ARG sindhu="hotboobs"
ENV sindhu=${sindhu}
RUN echo "Sudheer is a ${sudheer} vineela is ${vineela} sindhu is ${sindhu} "
CMD ["sleep", "100"]

# How do you check the OS of your server? cat /etc/*release