ARG version
FROM almalinux:${version:-6}
ARG sudheer="lazyboy"
ARG vineela="smartgirl"
RUN echo "Sudheer is a ${sudheer} vineela is ${vineela} "
CMD ["sleep", "100"]


# How do you check the OS of your server? cat /etc/*release